services:  
  ombi:
    image: linuxserver/ombi:latest
    container_name: ombi
    networks:
      - proxy
    environment:
      - BASE_URL=/ombi
    volumes:
      - /appdata/ombi_data:/config
    ports:
      - 3579:3579
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ombi.rule=Host(`ombi.grant.onl`)"
      - "traefik.http.routers.ombi.entrypoints=https"
      - "traefik.http.routers.secure.middlewares=default-whitelist"
      - "traefik.http.routers.ombi.tls.certresolver=cloudflare"
      - "traefik.http.services.ombi.loadbalancer.server.port=3001"
networks:
  proxy:
    external: true

