name: immich
services:
  immich-server:
    container_name: immich_server
    image: "ghcr.io/immich-app/immich-server:{{ docker.immich_version }}"
    volumes:
      - /appdata/immich_media:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: "ghcr.io/immich-app/immich-machine-learning:{{ docker.immich_version }}"
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: "{{ docker.immich_postgres_password }}"
      POSTGRES_USER: "{{ docker.immich_postgres_user }}"
      POSTGRES_DB: "{{ docker.immich_postgres_name }}"
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /appdata/immich_data:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="{{ docker.immich_postgres_name }}" --username="{{ docker.immich_postgres_user }}" || exit 1; Chksum="{{ docker.immich_postgres_name }}" --username="{{ docker.immich_postgres_user }}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always

volumes:
  model-cache:
