all:
  children:
    proxmox:
      hosts:
        Aesir:
          ansible_host: 192.168.0.5
          ansible_user: root
          connectx: true
          intel_sriov: true
          linstor: true
          linstor_controller: true
          linstor_disks: true
          linstor_pools:
            BulkPool:
              pool_name: BulkPool
              zfs_pool: hdd
              placecount: 2
              resource_group_name: RG-BulkPool
        Vanir:
          ansible_host: 192.168.0.6
          ansible_user: root
          connectx: true
          linstor: true
          linstor_controller: true
          linstor_disks: true
          linstor_pools:
            BulkPool:
              pool_name: BulkPool
              zfs_pool: hdd
              placecount: 2
              resource_group_name: RG-BulkPool
        Olympian:
          ansible_host: 192.168.0.7
          ansible_user: root
          connectx: true
          linstor: true
          linstor_controller: true
          linstor_controller_priority: 100
          linstor_disks: true # make true later when it has the needed disks?
          linstor_pools:
            DfltStorPool:
              pool_name: DfltStorPool
              zfs_pool: essd
              placecount: 2
              resource_group_name: RG-DfltStorPool
        Ennead:
          ansible_host: 192.168.0.8
          ansible_user: root
          connectx: true
          linstor: true
          linstor_controller: true
          linstor_controller_priority: 200
          linstor_initial_controller: true
          linstor_disks: true
          linstor_pools:
            DfltStorPool:
              pool_name: DfltStorPool
              zfs_pool: essd
              placecount: 2
              resource_group_name: RG-DfltStorPool
        Ogdoad:
          ansible_host: 192.168.0.9
          ansible_user: root
          connectx: true
          linstor: true
          linstor_controller: true
      vars:
        vip_ip: 192.168.0.4
    docker:
      hosts:
        # Main Docker host
        Beluga:
          ansible_host: 192.168.0.75
          ansible_user: bgrant
          docker_enabled: true
          template: "Arch-Server-Template"
          proxmox_host: Ennead
          storage: "linstor_DfltStorPool"
          size: 50
          docker_stacks:
            actual-budget: true
            lutris-hosting: true
            media: true
            portainer: true
            uptime-kuma: true
            vault-warden: true
        # Download suite
        Downloader:
          ansible_host: 192.168.0.76
          ansible_user: bgrant
          docker_enabled: true
          template: "Arch-Server-Template"
          ostype: "archlinux"
          proxmox_host: Olympian
          storage: "linstor_DfltStorPool"
          size: 50
          docker_stacks:
            download: true
          vm: true
        Orca:
          ansible_host: 192.168.0.77
          ansible_user: bgrant
          docker_enabled: true
          template: "Arch-Server-Template"
          ostype: "archlinux"
          proxmox_host: Ogdoad
          storage: "linstor_DfltStorPool"
          size: 250
          docker_stacks:
            immich: true
          vm: true
    tdarr:
      hosts:
        TdarrServer:
          ansible_host: 192.168.0.80
          ansible_user: root
          tdarr_server: true
          proxmox_host: Aesir
          interface: vmbr0
          subnet: /24
          gateway: 192.168.0.1
          template: "BulkPoolShared:vztmpl/custom-archlinux-2025-03-19.tar.zst"
          cpuunits: 75 # Give Tdarrserver less priority than normal (100)
          storage: linstor_DfltStorPool:50
          memory: 16384
          onboot: true
          ostype: "archlinux"
          tags: "tdarr"
          lxc: true
        TdarrNode01:
          ansible_host: 192.168.0.81
          ansible_user: root
          tdarr_node: true
          proxmox_host: Ennead
          interface: vmbr0
          subnet: /24
          gateway: 192.168.0.1
          template: "BulkPoolShared:vztmpl/custom-archlinux-2025-03-19.tar.zst"
          cpuunits: 50 # Give TdarrNode less priority than normal (100)
          storage: linstor_DfltStorPool:50
          memory: 16384
          onboot: true
          ostype: "archlinux"
          tags: "tdarr"
          lxc: true
        TdarrNode02:
          ansible_host: 192.168.0.82
          ansible_user: root
          tdarr_node: true
          proxmox_host: Ogdoad
          interface: vmbr0
          subnet: /24
          gateway: 192.168.0.1
          template: "BulkPoolShared:vztmpl/custom-archlinux-2025-03-19.tar.zst"
          cpuunits: 50 # Give TdarrNode less priority than normal (100)
          storage: linstor_DfltStorPool:50
          memory: 16384
          onboot: true
          ostype: "archlinux"
          tags: "tdarr"
          lxc: true
        TdarrNode03:
          ansible_host: 192.168.0.83
          ansible_user: root
          tdarr_node: true
          proxmox_host: Olympian
          interface: vmbr0
          subnet: /24
          gateway: 192.168.0.1
          template: "BulkPoolShared:vztmpl/custom-archlinux-2025-03-19.tar.zst"
          cpuunits: 50 # Give TdarrNode less priority than normal (100)
          storage: linstor_DfltStorPool:50
          memory: 16384
          onboot: true
          ostype: "archlinux"
          tags: "tdarr"
          lxc: true
        TdarrNode04:
          ansible_host: 192.168.0.84
          ansible_user: root
          tdarr_node: true
          proxmox_host: Vanir
          interface: vmbr0
          subnet: /24
          gateway: 192.168.0.1
          template: "BulkPoolShared:vztmpl/custom-archlinux-2025-03-19.tar.zst"
          cpuunits: 50 # Give TdarrNode less priority than normal (100)
          storage: linstor_DfltStorPool:50
          memory: 16384
          onboot: true
          ostype: "archlinux"
          tags: "tdarr"
          lxc: true
        TdarrNode05:
          ansible_host: 192.168.0.85
          ansible_user: root
          tdarr_node: true
          proxmox_host: Aesir
          interface: vmbr0
          subnet: /24
          gateway: 192.168.0.1
          template: "BulkPoolShared:vztmpl/custom-archlinux-2025-03-19.tar.zst"
          cpuunits: 50 # Give TdarrNode less priority than normal (100)
          storage: linstor_DfltStorPool:50
          memory: 16384
          onboot: true
          ostype: "archlinux"
          tags: "tdarr"
          lxc: true
