all:
  vars:
    clone_home: Vanir
  children:
    proxmox:
      hosts:
        Aesir:
          ansible_host: 192.168.0.5
          ansible_user: root
          connectx: true
          intel_sriov: true
          linstor: true
          linstor_controller: true
          linstor_disks: true
          linstor_pools:
            BulkPool:
              pool_name: BulkPool
              zfs_pool: hdd
              placecount: 2
              resource_group_name: RG-BulkPool
        Vanir:
          ansible_host: 192.168.0.6
          ansible_user: root
          connectx: true
          linstor: true
          linstor_controller: true
          linstor_disks: true
          linstor_pools:
            BulkPool:
              pool_name: BulkPool
              zfs_pool: hdd
              placecount: 2
              resource_group_name: RG-BulkPool
        Olympian:
          ansible_host: 192.168.0.7
          ansible_user: root
          connectx: true
          linstor: true
          linstor_controller: true
          linstor_controller_priority: 100
          linstor_disks: true # make true later when it has the needed disks?
          linstor_pools:
            DfltStorPool:
              pool_name: DfltStorPool
              zfs_pool: essd
              placecount: 2
              resource_group_name: RG-DfltStorPool
        Ennead:
          ansible_host: 192.168.0.8
          ansible_user: root
          connectx: true
          linstor: true
          linstor_controller: true
          linstor_controller_priority: 200
          linstor_initial_controller: true
          linstor_disks: true
          linstor_pools:
            DfltStorPool:
              pool_name: DfltStorPool
              zfs_pool: essd
              placecount: 2
              resource_group_name: RG-DfltStorPool
        Ogdoad:
          ansible_host: 192.168.0.9
          ansible_user: root
          connectx: true
          linstor: true
          linstor_controller: true
        PBS:
          # Not a hypervisor but a backup server
          # This is a virtual machine
          ansible_host: 192.168.0.12
          ansible_user: root
      vars:
        vip_ip: 192.168.0.4
    docker:
      hosts:
        Downloader:
          ansible_host: 192.168.0.76
          ansible_user: bgrant
          docker_enabled: true
          template: "Arch-Server-Template"
          ostype: "archlinux"
          proxmox_host: Olympian
          storage: "linstor_DfltStorPool"
          size: 50G
          docker_stacks:
            download: true
          vm: true
        Orca:
          ansible_host: 192.168.0.77
          interface: vmbr0
          subnet: /24
          gateway: 192.168.0.1
          ansible_user: bgrant
          docker_enabled: true
          template: "Arch-Server-Template"
          ostype: "archlinux"
          proxmox_host: Ennead
          storage: "essd"
          size: 250G
          memory: 8192
          vcpus: 8
          docker_stacks:
            immich: true
            unifi: true
            dns: false
            traefik: true
            actual-budget: true
            vault-warden: true
            media: true
            lutris-hosting: true
            download: true
            ombi: true
          vm: true
          proxmox_tags:
            - docker
    tdarr:
      hosts:
        TdarrServer:
          ansible_user: bgrant
          ansible_become: true
          ansible_become_method: sudo
          ansible_host: 192.168.0.80
          tdarr_server: true
          proxmox_host: Aesir
          interface: vmbr0
          subnet: /24
          gateway: 192.168.0.1
          template: "Arch-Server-Template"
          cpuunits: 75 # Give Tdarrserver less priority than normal (100)
          storage: "linstor_DfltStorPool"
          size: 50G
          memory: 16384
          sockets: 1
          cores: 8
          vcpus: 8
          onboot: true
          ostype: "archlinux"
          proxmox_tags:
            - tdarr
          vm: true
        TdarrNode01:
          ansible_user: bgrant
          ansible_become: true
          ansible_become_method: sudo
          ansible_host: 192.168.0.81
          tdarr_node: true
          proxmox_host: Ennead
          interface: vmbr0
          subnet: /24
          gateway: 192.168.0.1
          template: "Arch-Server-Template"
          cpuunits: 50 # Give TdarrNode less priority than normal (100)
          storage: "linstor_DfltStorPool"
          size: 50G
          memory: 16384
          sockets: 2
          cores: 28
          vcpus: 50
          onboot: true
          ostype: "archlinux"
          proxmox_tags:
            - tdarr
            - immobile
          vm: true
        TdarrNode02:
          ansible_user: bgrant
          ansible_become: true
          ansible_become_method: sudo
          ansible_host: 192.168.0.82
          tdarr_node: true
          proxmox_host: Ogdoad
          interface: vmbr0
          subnet: /24
          gateway: 192.168.0.1
          template: "Arch-Server-Template"
          cpuunits: 50 # Give TdarrNode less priority than normal (100)
          storage: "linstor_DfltStorPool"
          size: 50G
          memory: 16384
          sockets: 2
          cores: 28
          vcpus: 50
          onboot: true
          ostype: "archlinux"
          proxmox_tags:
            - tdarr
            - immobile
          vm: true
        TdarrNode03:
          ansible_user: bgrant
          ansible_become: true
          ansible_become_method: sudo
          ansible_host: 192.168.0.83
          tdarr_node: true
          proxmox_host: Olympian
          interface: vmbr0
          subnet: /24
          gateway: 192.168.0.1
          template: "Arch-Server-Template"
          cpuunits: 50 # Give TdarrNode less priority than normal (100)
          storage: "linstor_DfltStorPool"
          size: 50G
          memory: 16384
          sockets: 2
          cores: 28
          vcpus: 50
          onboot: true
          ostype: "archlinux"
          proxmox_tags:
            - tdarr
            - immobile
          vm: true
        TdarrNode04:
          ansible_user: bgrant
          ansible_become: true
          ansible_become_method: sudo
          ansible_host: 192.168.0.84
          tdarr_node: true
          proxmox_host: Vanir
          interface: vmbr0
          subnet: /24
          gateway: 192.168.0.1
          template: "Arch-Server-Template"
          cpuunits: 50 # Give TdarrNode less priority than normal (100)
          storage: "linstor_DfltStorPool"
          size: 50G
          memory: 16384
          sockets: 1
          cores: 24
          vcpus: 20
          onboot: true
          ostype: "archlinux"
          proxmox_tags:
            - tdarr
            - immobile
          vm: true
        TdarrNode05:
          ansible_user: bgrant
          ansible_become: true
          ansible_become_method: sudo
          ansible_host: 192.168.0.85
          tdarr_node: true
          proxmox_host: Aesir
          interface: vmbr0
          subnet: /24
          gatANSIBLE_CONFIGeway: 192.168.0.1
          template: "Arch-Server-Template"
          cpuunits: 50 # Give TdarrNode less priority than normal (100)
          storage: "linstor_DfltStorPool"
          size: 50G
          memory: 16384
          sockets: 1
          cores: 20
          vcpus: 18
          onboot: true
          ostype: "archlinux"
          proxmox_tags:
            - tdarr
            - immobile
          vm: true
    SemaphoreUI:
      hosts:
        SemaphoreUI:
          ansible_user: bgrant
          ansible_become: true
          ansible_become_method: sudo
          ansible_host: 192.168.0.20
          proxmox_host: Aesir
          interface: vmbr0
          subnet: /24
          gateway: 192.168.0.1
          template: "Arch-Server-Template"
          storage: "linstor_DfltStorPool"
          size: 50G
          memory: 2048
          vcpus: 4
          onboot: true
          ostype: "archlinux"
          proxmox_tags:
            - code
          vm: true
