services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /appdata/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    devices:
      # relies on udev rule on host
      # /etc/udev/rules.d/99-usb-serial.rules
      # SUBSYSTEM=="tty",
      # KERNEL=="ttyACM[0-9]*",
      # ATTRS{product}=="ConBee II",
      # ATTRS{serial}=="DE2463123",
      # ATTRS{manufacturer}=="dresden elektronik ingenieurtechnik GmbH",
      # SYMLINK+="ttyZigbeeRadio"
      - /dev/ttyZigbeeRadio:/dev/ttyZigbeeRadio
  zwave-js-ui:
    container_name: zwave-js-ui
    image: zwavejs/zwave-js-ui:latest
    restart: unless-stopped
    tty: true
    network_mode: host
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=${zwave_secret}
      - TZ=America/New_York
    devices:
      # relies on udev rule on host
      # /etc/udev/rules.d/99-usb-serial.rules
      # SUBSYSTEM=="tty",
      # KERNEL=="ttyACM[0-9]*",
      # ATTRS{manufacturer}=="Zooz"
      # ATTRS{product}=="800 Z-Wave Stick"
      # ATTRS{serial}=="533D004242"
      # SYMLINK+="ttyZwaveRadio"
      - /dev/ttyZwaveRadio:/dev/ttyZwaveRadio
    volumes:
      - /appdata/zwave-config:/usr/src/app/store
# Not needed if running host networking left for reference
#    ports:
#      - '8091:8091' # port for web interface
#      - '3000:3000' # port for Z-Wave JS websocket server

