# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: lutris
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=000
      - TZ=America/Toronto
    volumes:
      - /appdata/lutris_data:/config
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lutris.rule=Host(`lutris.grant.onl`)"
      - "traefik.http.routers.lutris.entrypoints=https"
      - "traefik.http.routers.lutris.tls.certresolver=cloudflare"
      - "traefik.http.services.lutris.loadbalancer.server.port=80"
networks:
  proxy:
    external: true
