# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=000
      - TZ=America/Toronto
    volumes:
      - /appdata/lutris_data:/config
    ports:
      - 10002:80
    restart: unless-stopped

