# I may just want to roll this into the media stack
services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - kavita_data:/config
      - books:/data
    ports:
      - 5000:5000
    restart: unless-stopped
volumes: 
  books:
    driver: local
    driver_opts:
      type: nfs
      o: "addr={{ NAS_IP }},rw,nfsvers=4.2,nconnect=8"
      device: ":/mnt/Mass/Media/Books"
  kavita_data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr={{ NAS_IP }},rw,nfsvers=4.2,nconnect=8"
      device: ":/mnt/Zoom/docker/kavita_data"