# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    networks:
      - proxy
    volumes:
      - /appdata/actual_budget_data:/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.actual-budget.rule=Host(`budget.grant.onl`)"
      - "traefik.http.routers.actual-budget.entrypoints=https"
      - "traefik.http.routers.secure.middlewares=default-whitelist"
      - "traefik.http.routers.actual-budget.tls.certresolver=cloudflare"
      - "traefik.http.services.actual-budget.loadbalancer.server.port=5006"
networks:
  proxy:
    external: true
