# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    networks:
      - proxy
    volumes:
      - /appdata/uptime_data:/app/data
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime.rule=Host(`uptimekuma.grant.onl`)"
      - "traefik.http.routers.uptime.entrypoints=https"
      - "traefik.http.routers.uptime.middlewares=default-whitelist@file,default-headers@file"
      - "traefik.http.routers.uptime.tls.certresolver=cloudflare"
      - "traefik.http.services.uptime.loadbalancer.server.port=3001"
networks:
  proxy:
    external: true

