---
- name: Deploy Semaphore
  hosts: SemaphoreUI
  gather_facts: false
  remote_user: "{{ hostvars[inventory_hostname].ansible_user }}"
  become: true
  vars_files:
    - vault/vault.yml
  vars:
    ansible_shell_executable: /bin/bash  # Use bash as the default shell
    ansible_ssh_pipelining: true
  tasks:
    - name: Debug Ostype value
      ansible.builtin.debug:
        msg: "Ostype is: {{ hostvars[inventory_hostname].ostype | default(none) }}"

    - name: Run deploy-proxmox-container to ensure the required LXC exists
      ansible.builtin.include_role:
        name: deploy-proxmox-container
      when: (hostvars[inventory_hostname].lxc | default(false) | bool)

    - name: Run deploy-proxmox-vm to ensure the required VM exists
      ansible.builtin.include_role:
        name: deploy-proxmox-vm
      when: (hostvars[inventory_hostname].vm | default(false) | bool)

    - name: Ensure the service user exists
      ansible.builtin.user:
        name: semaphore
        system: true
        shell: /usr/sbin/nologin
        home: /home/semaphore
        create_home: true

    - name: Ensure Semaphore Directory Exists
      ansible.builtin.file:
        path: /home/semaphore
        state: directory
        owner: semaphore
        group: semaphore
        mode: '0755'

    - name: Create requirements.txt
      ansible.builtin.template:
        src: requirements.txt
        dest: /home/semaphore/requirements.txt
        owner: semaphore
        group: semaphore
        mode: '0774'

    - name: Create requirements.yml
      ansible.builtin.template:
        src: requirements.yml
        dest: /home/semaphore/requirements.yml
        owner: semaphore
        group: semaphore
        mode: '0774'

    - name: Run the arch-update role to update and prep arch based systems
      ansible.builtin.include_role:
        name: arch-update
      when: (hostvars[inventory_hostname].ostype | default('')) == "archlinux"

    - name: Run the oh my posh role for apt systems so we can have a pretty cli
      ansible.builtin.include_role:
        name: oh-my-posh-apt
      when: (hostvars[inventory_hostname].ostype | default('')) in ["ubuntu", "debian"]

    - name: Run the oh my posh role for arch systems so we can have a pretty cli
      ansible.builtin.include_role:
        name: oh-my-posh-arch
      when: (hostvars[inventory_hostname].ostype | default('')) == "archlinux"

    - name: Install SemaphoreUI
      ansible.builtin.include_role:
        name: semaphoreui
