---
- name: Test whatever role we are working on
  hosts: Aesir
  vars_files:
    - vault/vault.yml
  vars:
    ansible_shell_executable: /bin/bash  # Use bash as the default shell
    ansible_ssh_pipelining: true
  # tasks:
  roles:
    - evacuate-proxmox-node
